# Generated by Django 4.2.7 on 2023-11-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht11',
            name='CO_2',
            field=models.FloatField(null=True),
        ),
    ]
